server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/facebook
    username: root
    password: Dinhvuanh123@
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

security:
  jwt:
    token:
      secret-key: thisissecretkeyfordemoangularapp
      expire-length: 3600000
      expire-refresh-token: 604800000